aarm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: revolute
    pid: {p: 10000.0, i: 0.01, d: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: continuous
    pid: {p: 1000.0, i: 0.01, d: 10.0}
